# Generated by Django 5.2.7 on 2025-11-03 23:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official airline name', max_length=200)),
                ('iata_code', models.CharField(help_text='IATA airline code (e.g., BA, AA, LH)', max_length=3, unique=True)),
                ('icao_code', models.CharField(help_text='ICAO airline code (e.g., BAW, AAL, DLH)', max_length=4, unique=True)),
                ('callsign', models.CharField(help_text='Radio callsign', max_length=50)),
                ('country', models.CharField(help_text='ISO country code', max_length=3)),
                ('headquarters', models.CharField(max_length=200)),
                ('hub_airports', models.TextField(help_text='Main hub airports (comma-separated IATA codes)')),
                ('destinations', models.IntegerField(default=0, help_text='Number of destinations served')),
                ('fleet_size', models.IntegerField(default=0, help_text='Total number of aircraft')),
                ('fleet_types', models.TextField(help_text='Aircraft types in fleet (comma-separated)')),
                ('founded_year', models.IntegerField(help_text='Year the airline was founded', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_hiring', models.BooleanField(default=False, help_text='Currently hiring pilots/crew')),
                ('hiring_regions', models.TextField(blank=True, help_text="Regions where they're hiring (comma-separated country codes)")),
                ('pilot_requirements', models.TextField(blank=True, help_text='Minimum requirements for pilots (licenses, hours, etc.)')),
                ('pilot_salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum pilot salary (USD per year)', max_digits=10, null=True)),
                ('pilot_salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum pilot salary (USD per year)', max_digits=10, null=True)),
                ('cabin_crew_requirements', models.TextField(blank=True, help_text='Requirements for cabin crew positions')),
                ('cabin_crew_salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cabin crew salary (USD per year)', max_digits=10, null=True)),
                ('cabin_crew_salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cabin crew salary (USD per year)', max_digits=10, null=True)),
                ('benefits', models.TextField(blank=True, help_text='Employee benefits (travel perks, insurance, etc.)')),
                ('training_programs', models.TextField(blank=True, help_text='Available training programs')),
                ('contact_hr', models.EmailField(blank=True, help_text='HR contact email', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AirlineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PILOT', 'Pilot'), ('CABIN_CREW', 'Cabin Crew'), ('GROUND_STAFF', 'Ground Staff'), ('MAINTENANCE', 'Maintenance'), ('MANAGEMENT', 'Management'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('overall_rating', models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('work_life_balance', models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('compensation', models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('management', models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('career_growth', models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('years_experience', models.IntegerField(help_text='Years of experience in aviation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('employment_status', models.CharField(choices=[('CURRENT', 'Current Employee'), ('FORMER', 'Former Employee')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='airlines.airline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
